apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: end-to-end-app
  version: v1.0.0

images:
  - name: omarzaki222/end-to-end-project
    newTag: latest
