apiVersion: v1
kind: PersistentVolume
metadata:
  name: end-to-end-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /data/end-to-end-app
