apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: end-to-end-pvc
  namespace: flask-app-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi